### PR TITLE
Do not call `zero(T)` from generated function body

### LINKED ISSUE #231: World age problem when 'using' Measurements after Unitful
When converting a Measurement in Kelvin to Celsius I get the following error:
```
julia> using Unitful

julia> using Measurements

julia> uconvert(u"°C", 300.0u"K")
26.850000000000023 °C

julia> uconvert(u"°C", (300.0 ± 0.5)u"K")
ERROR: MethodError: no method matching Measurement{Float64}(::Int64)
The applicable method may be too new: running in world age 25569, while current world is 25578.
Closest candidates are:
  Measurement{Float64}(::Real, ::RoundingMode) where T<:AbstractFloat at rounding.jl:194
  Measurement{Float64}(::Any, ::Any, ::Any, ::Any) where T<:AbstractFloat at /users/kwessel/.julia/packages/Measurements/VjRMd/src/Measurements.jl:50 (method too new to be called from this world context.)
  Measurement{Float64}(::S) where {T, S} at /users/kwessel/.julia/packages/Measurements/VjRMd/src/Measurements.jl:61 (method too new to be called from this world context.)
  ...
Stacktrace:
 [1] convert(::Type{Measurement{Float64}}, ::Int64) at ./number.jl:7
 [2] zero(::Type{Measurement{Float64}}) at ./number.jl:263
 [3] #s39#149 at /users/kwessel/.julia/packages/Unitful/W0mMi/src/conversion.jl:43 [inlined]
 [4] #s39#149(::Any, ::Any, ::Any) at ./none:0
 [5] (::Core.GeneratedFunctionStub)(::Any, ::Vararg{Any,N} where N) at ./boot.jl:522
 [6] uconvert(::Unitful.FreeUnits{(K,),𝚯,Unitful.Affine{-5463//20}}, ::Quantity{Measurement{Float64},𝚯,Unitful.FreeUnits{(K,),𝚯,nothing}}) at /users/kwessel/.julia/packages/Unitful/W0mMi/src/conversion.jl:21
 [7] top-level scope at none:0
```

However if I reverse the `using` statements everything works fine:
```
julia> using Measurements

julia> using Unitful

julia> uconvert(u"°C", 300.0u"K")
26.850000000000023 °C

julia> uconvert(u"°C", (300.0 ± 0.5)u"K")
26.850000000000023 ± 0.5 °C
```

I tested this with Julia 1.1 and 
```
(tmp) pkg> status
    Status `/tmp/test`
  [eff96d63] Measurements v2.0.0
  [1986cc42] Unitful v0.15.0
```

I don't know if this is a problem with Unitful or Measurements or both. However I posted the ticket at [Measurements](https://github.com/JuliaPhysics/Measurements.jl/issues/42) first and giordano was able to reproduce the problem with only Unitful:

```
julia> using Unitful

julia> module Foos
       export Foo
       struct Foo{T<:Real} <: Real
           a::T
       end
       end
Main.Foos

julia> using Main.Foos

julia> uconvert(u"°C", Foo(300)u"K")
ERROR: MethodError: no method matching Foo{Int64}(::Int64)
The applicable method may be too new: running in world age 25569, while current world is 25573.
Closest candidates are:
  Foo{Int64}(::Any) where T<:Real at REPL[2]:4 (method too new to be called from this world context.)
Stacktrace:
 [1] convert(::Type{Foo{Int64}}, ::Int64) at ./number.jl:7
 [2] zero(::Type{Foo{Int64}}) at ./number.jl:263
 [3] #s39#149 at /home/mose/.julia/packages/Unitful/W0mMi/src/conversion.jl:43 [inlined]
 [4] #s39#149(::Any, ::Any, ::Any) at ./none:0
 [5] (::Core.GeneratedFunctionStub)(::Any, ::Vararg{Any,N} where N) at ./boot.jl:522
 [6] uconvert(::Unitful.FreeUnits{(K,),𝚯,Unitful.Affine{-5463//20}}, ::Quantity{Foo{Int64},𝚯,Unitful.FreeUnits{(K,),𝚯,nothing}}) at /home/mose/.julia/packages/Unitful/W0mMi/src/conversion.jl:21
 [7] top-level scope at none:0
```

### PR DESCRIPTION
**Pull request by c42f**
This avoids world age errors for user defined types `T`.

Fixes #231

### CODE REVIEW

**Comment by karlwessel** [comment]
I've tested this PR and can confirm that it fixes my problem from #231:
```
julia> using Unitful

julia> using Measurements

julia> uconvert(u"°C", 300.0u"K")
26.850000000000023 °C

julia> uconvert(u"°C", (300.0 ± 0.5)u"K")
26.850000000000023 ± 0.5 °C
```
Thank you!

File: test/runtests.jl [hunk 1]
```diff
@@ -1498,4 +1498,18 @@ end
     @test isa(TUM.fu^2, TUM.FakeDim212345Units)
 end
 
+
+struct Num <: Real
+   x::Float64
+end
+Base.:+(a::Num, b::Num) = Num(a.x - b.x)
```
Comment (ajkeller34) [inline test/runtests.jl]: `Num(a.x + b.x)`?

**Comment by ajkeller34** [comment]
Merged in [rigetti/Unitful.jl](https://github.com/rigetti/Unitful.jl/pull/4), which is where I'll be maintaining Unitful.jl from now on.

**Comment by c42f** [comment]
How about transferring the repo to Rigetti? Then you will bring all the issues and PRs along, preserving that part of the history of the project.

**Comment by ajkeller34** [comment]
I'm not able to do that, see https://github.com/PainterQubits/Unitful.jl/issues/228#issuecomment-490344695
