### PR TITLE
Fix conversions between `rpm`, `rps`, and other rotational units.

### LINKED ISSUE #261: conversion from RPM to rad/s is incorrect
Because there is no default `turn` or `rotation` unit defined, conversion from rpm or rps to rad/s gives incorrect results. As an example `1rps |> rad/s` should result in `2*pi rad/s` but the conversion pipeline results in `1//1 rad s^-1` which is incorrect. Changing the definition of RPM to `(2*pi)rad/minute` fixes the problem but requires rad be defined and may cause other problems I'm not familiar with.

### PR DESCRIPTION
**Pull request by ajkeller34**
Closes #261.

### CODE REVIEW

**Comment by ajkeller34** [comment]
I'd like to keep this open for a couple days to see if there are any objections. In particular, I think the previous definition of `Hz` was also wrong. I'm surprised nobody complained about it before given how common of a unit `Hz` is, which is why I'm nervous to merge this.

File: src/pkgdefaults.jl [hunk 1]
```diff
@@ -71,7 +71,8 @@ for (_x,_y) in ((:sin,:sind), (:cos,:cosd), (:tan,:tand),
 end
 
 # SI and related units
-@unit Hz     "Hz"       Hertz       1/s                     true
+@unit cycle  "cycle"    Cycle       2π*rad                  false
+@unit Hz     "Hz"       Hertz       1cycle/s                true
```
Comment (giordano) [inline src/pkgdefaults.jl]: Wait, what? https://en.wikipedia.org/wiki/Hertz

Comment (ajkeller34) [reply src/pkgdefaults.jl]: > The hertz (symbol: Hz) is the derived unit of frequency in the International System of Units (SI) and is defined as one cycle per second.[1] 

> ... a disc rotating at 60 revolutions per minute (rpm) is said to be rotating at either 2π rad/s or 1 Hz.

With this PR:

```
julia> 2π*u"rad/s" == 1u"Hz" == 60u"rpm"
true
```

on master:

```
julia> 2π*u"rad/s" == 1u"Hz" == 60u"rpm"
false
```

Comment (giordano) [reply src/pkgdefaults.jl]:
```julia
julia> uconvert(u"s^-1", 1u"Hz")
6.283185307179586 s^-1
```
This is just wrong

Comment (giordano) [reply src/pkgdefaults.jl]: On master:
```julia
julia> using Unitful, PhysicalConstants.CODATA2018

julia> uconvert(u"Hz / K", BoltzmannConstant / PlanckConstant)
2.0836619123327576e10 Hz K^-1
```
With this PR:
```julia
julia> using Unitful, PhysicalConstants.CODATA2018

julia> uconvert(u"Hz / K", BoltzmannConstant / PlanckConstant)
3.3162509308006988e9 Hz K^-1
```
Correct result: https://physics.nist.gov/cgi-bin/cuu/Value?kshhz

Comment (ajkeller34) [reply src/pkgdefaults.jl]: I routinely consider `1Hz` as `1/s` myself, so don't get me wrong, I'm also a bit surprised. I'm just not sure how to avoid a contradiction unless things are defined this way. 

It is as if `1/s` cannot be read as "once per second," because without explicit angular units, radians are implicit (circumference in meters = 2π * length in meters). If we're explicit with `1cycle/s`, it is hard to disagree that a cycle is 2π radians, and so I think everything is correct. That's not to say this wouldn't break a lot of user code...

Comment (ajkeller34) [reply src/pkgdefaults.jl]: I would very much welcome alternative suggestions to fix the reported issue without breaking other conversions.

Comment (ajkeller34) [reply src/pkgdefaults.jl]: The root of the problem is that `2π == 2π * rad`; from units alone we cannot distinguish angular frequency from Hz.

Comment (giordano) [reply src/pkgdefaults.jl]: I think there is a misunderstanding with the meaning of "cycle": https://en.wikipedia.org/wiki/Cycle_per_second.  Numerically it's just `1::Int`.  It doesn't measure the length of an arc.

Comment (giordano) [reply src/pkgdefaults.jl]: > ... a disc rotating at 60 revolutions per minute (rpm) is said to be rotating at either 2π rad/s or 1 Hz.

Isn't 2π rad/s an angular velocity?  Why it should be equal to a frequency?

Comment (ajkeller34) [reply src/pkgdefaults.jl]: I'll revert the commit for `Hz`, but something is still broken. We're now back to 

```
julia> 1u"Hz" == 2π * u"rad/s"
false
```

Comment (giordano) [reply src/pkgdefaults.jl]: Which I think is right?  Isn't angular velocity 2pi times the frequency?
```julia
julia> uconvert(u"Hz", 2π*u"rad/s")
6.283185307179586 Hz
```

Comment (ajkeller34) [reply src/pkgdefaults.jl]: Perhaps I'm not thinking about this clearly today given the US holiday weekend so feel free to mark this as resolved if you're sure it's right now, but I'm concerned that people will expect that the conversion to angular frequency will happen automatically as part of a unit conversion:

```
julia> uconvert(u"rad/s", 1u"Hz")
1//1 rad s^-1
```

Shouldn't this be 2pi times the frequency?

Comment (ajkeller34) [reply src/pkgdefaults.jl]: > > ... a disc rotating at 60 revolutions per minute (rpm) is said to be rotating at either 2π rad/s or 1 Hz.
> 
> Isn't 2π rad/s an angular velocity? Why it should be equal to a frequency?

Dimensionally, angular velocity and frequency are the same, if you subscribe to the view that angles are dimensionless. This issue has cropped up before in Unitful discussions. I think it may be a limitation of the package design, in that there is no way to distinguish by type an angular velocity from a frequency.

Comment (giordano) [reply src/pkgdefaults.jl]: Yes, exactly, angular velocity and frequency of a circular motion share the same physical dimensions but are scaled by a constant factor.

I don't find the result of `uconvert(u"rad/s", 1u"Hz")` surprising. I see 1 Hertz as one (dimensionless) "thing" per second. One radian happens to be a dimensionless quantity, so 1 radian per second is just that one "thing" per second.

I don't think it's this package job's to convert between different physical quantities that refer to the same motion and by chance share the same physical dimensions, this is more on the user side.

Comment (ajkeller34) [reply src/pkgdefaults.jl]: > I don't think it's this package job's to convert between different physical quantities that refer to the same motion and by chance share the same physical dimensions, this is more on the user side.

Ok, I buy that. I'll mark this as resolved and squash+merge the PR. I think the confusion came from our differing presumptions about what `uconvert` should do, but your view seems more consistent. Thanks for the input.

**Comment by gustaphe** [comment]
I know I'm a bit late to the party but I do object to this. I would expect `60rpm == 1Hz == 1/s`. To get an angular frequency (in radians/minute) corresponding to 1 *revolution* per minute, you take `ω = 2π*f`. This tripped me up bad recently.
