### PR TITLE
Resolve remaining method ambiguities

### LINKED ISSUE #469: `floor` with degrees (`NoUnits`) and `digits` fails due to method ambiguity
MWE:

```julia
using Unitful: mm, °

x = 3.001mm
floor(typeof(x), x, digits=2) # works

a = 3.001°
floor(typeof(a), a, digits=2) # fails due to method ambiguity
```

Presumably because degrees are the `NoUnits` flavor.
This one is pretty opaque to me so I'm not sure where to begin for PR.

Perhaps related to #326?
In fact I suspect that if #328 were merged then I probably would just use `floor(a, digits=2)` for my use case (matching how non-unit values work), so it would be great to bump that one!

### LINKED ISSUE #604: Fix method ambiguities
After adding Aqua.jl automatic testing to a package which depends on Unitful, I found the tests failing due to method ambiguities within Unitful. Adding Aqua to a dev-d Unitful, the following ambiguities appear:
```
23 ambiguities found
Ambiguity #1
(Unitful.Quantity{<:Any, D, U})(val) where {D, U} @ Unitful C:\Users\aames\.julia\dev\Unitful\src\types.jl:156
(::Type{T})(x::T) where T<:Number @ Core boot.jl:792

Possible fix, define
  (Unitful.Quantity{<:Any, D, U})(::Unitful.Quantity{<:Any, D, U}) where {D, U}

Ambiguity #2
*(x::Unitful.Gain, y::Number) @ Unitful C:\Users\aames\.julia\dev\Unitful\src\logarithm.jl:214
*(y::Number, x::Unitful.AbstractQuantity) @ Unitful C:\Users\aames\.julia\dev\Unitful\src\quantities.jl:32

Possible fix, define
  *(::Unitful.Gain, ::Unitful.AbstractQuantity)

Ambiguity #3
Unitful.Level{L, S, T}(x) where {L, S, T} @ Unitful C:\Users\aames\.julia\dev\Unitful\src\types.jl:241
(::Type{T})(x::T) where T<:Number @ Core boot.jl:792

Possible fix, define
  Unitful.Level{L, S, T}(::Unitful.Level{L, S, T}) where {L, S, T}

Ambiguity #4
(Unitful.Quantity{<:Any, D, U})(val) where {D, U} @ Unitful C:\Users\aames\.julia\dev\Unitful\src\types.jl:156
(::Type{T})(x::Base.TwicePrecision) where T<:Number @ Base twiceprecision.jl:266

Possible fix, define
  (Unitful.Quantity{<:Any, D, U})(::Base.TwicePrecision) where {D, U}

Ambiguity #5
/(x::Unitful.Level, y::Number) @ Unitful C:\Users\aames\.julia\dev\Unitful\src\logarithm.jl:243
/(x::Number, y::Unitful.AbstractQuantity) @ Unitful C:\Users\aames\.julia\dev\Unitful\src\quantities.jl:57

Possible fix, define
  /(::Unitful.Level, ::Unitful.AbstractQuantity)

Ambiguity #6
_promote_unit(x::Unitful.ContextUnits{N, D, P1, A}, y::Unitful.ContextUnits{N, D, P2, A}) where {N, D, P1, P2, A} @ Unitful C:\Users\aames\.julia\dev\Unitful\src\promotion.jl:30
_promote_unit(x::Unitful.ContextUnits{N1, D, P}, y::Unitful.ContextUnits{N2, D, P}) where {N1, N2, D, P} @ Unitful C:\Users\aames\.julia\dev\Unitful\src\promotion.jl:33

Possible fix, define
  _promote_unit(::Unitful.ContextUnits{N1, D, P, A}, ::Unitful.ContextUnits{N1, D, P, A}) where {N1, D, P, A}

Ambiguity #7
promote_rule(::Type{T}, ::Type{Unitful.Level{L, R, S}}) where {L, R, S, T<:Real} @ Unitful C:\Users\aames\.julia\dev\Unitful\src\logarithm.jl:289
promote_rule(::Type{Bool}, ::Type{T}) where T<:Number @ Base bool.jl:4

Possible fix, define
  promote_rule(::Type{Bool}, ::Type{Unitful.Level{L, R, S}}) where {L, R, S}

Ambiguity #8
(T::Type{<:Unitful.AbstractQuantity})(period::Dates.CompoundPeriod) @ Unitful C:\Users\aames\.julia\dev\Unitful\src\dates.jl:135
(Unitful.Quantity{<:Any, D, U})(val) where {D, U} @ Unitful C:\Users\aames\.julia\dev\Unitful\src\types.jl:156

Possible fix, define
  (Unitful.Quantity{<:Any, D, U})(::Dates.CompoundPeriod) where {D, U}

Ambiguity #9
//(x::Unitful.Level, y::Number) @ Unitful C:\Users\aames\.julia\dev\Unitful\src\logarithm.jl:244
//(x::Number, y::Unitful.AbstractQuantity) @ Unitful C:\Users\aames\.julia\dev\Unitful\src\quantities.jl:60

Possible fix, define
  //(::Unitful.Level, ::Unitful.AbstractQuantity)

Ambiguity #10
*(x::Number, y::Unitful.Gain) @ Unitful C:\Users\aames\.julia\dev\Unitful\src\logarithm.jl:220
*(x::Unitful.AbstractQuantity, y::Number) @ Unitful C:\Users\aames\.julia\dev\Unitful\src\quantities.jl:33

Possible fix, define
  *(::Unitful.AbstractQuantity, ::Unitful.Gain)

Ambiguity #11
//(x::Number, y::Unitful.Level) @ Unitful C:\Users\aames\.julia\dev\Unitful\src\logarithm.jl:251
//(x::Unitful.AbstractQuantity, y::Number) @ Unitful C:\Users\aames\.julia\dev\Unitful\src\quantities.jl:59

Possible fix, define
  //(::Unitful.AbstractQuantity, ::Unitful.Level)

Ambiguity #12
(var"#ctor-self#"::Type{Unitful.Gain{L, S, T}} where {L, S, T<:Real})(val) @ Unitful C:\Users\aames\.julia\dev\Unitful\src\types.jl:257
(::Type{T})(x::AbstractChar) where T<:Union{AbstractChar, Number} @ Base char.jl:50

Possible fix, define
  Unitful.Gain{L, S, T}(::AbstractChar) where {L, S, T<:Real}

Ambiguity #13
*(x::Number, y::Unitful.Level) @ Unitful C:\Users\aames\.julia\dev\Unitful\src\logarithm.jl:209
*(x::Unitful.AbstractQuantity, y::Number) @ Unitful C:\Users\aames\.julia\dev\Unitful\src\quantities.jl:33

Possible fix, define
  *(::Unitful.AbstractQuantity, ::Unitful.Level)

Ambiguity #14
promote_rule(::Type{T}, ::Type{Unitful.Level{L, R, S}}) where {L, R, S, T<:Real} @ Unitful C:\Users\aames\.julia\dev\Unitful\src\logarithm.jl:289
promote_rule(::Type{S}, ::Type{T}) where {S<:AbstractIrrational, T<:Number} @ Base irrationals.jl:45

Possible fix, define
  promote_rule(::Type{S}, ::Type{Unitful.Level{L, R, S}}) where {S<:AbstractIrrational, L, R, S}

Ambiguity #15
*(x::Unitful.Level, y::Number) @ Unitful C:\Users\aames\.julia\dev\Unitful\src\logarithm.jl:203
*(y::Number, x::Unitful.AbstractQuantity) @ Unitful C:\Users\aames\.julia\dev\Unitful\src\quantities.jl:32

Possible fix, define
  *(::Unitful.Level, ::Unitful.AbstractQuantity)

Ambiguity #16
(var"#ctor-self#"::Type{Unitful.Gain{L, S, T}} where {L, S, T<:Real})(val) @ Unitful C:\Users\aames\.julia\dev\Unitful\src\types.jl:257
(::Type{T})(x::T) where T<:Number @ Core boot.jl:792

Possible fix, define
  Unitful.Gain{L, S, T}(::Unitful.Gain{L, S, T}) where {L, S, T<:Real}

Ambiguity #17
fma(x::Number, y::Unitful.AbstractQuantity, z::Unitful.AbstractQuantity) @ Unitful C:\Users\aames\.julia\dev\Unitful\src\quantities.jl:184
fma(x::Unitful.AbstractQuantity, y::Number, z::Unitful.AbstractQuantity) @ Unitful C:\Users\aames\.julia\dev\Unitful\src\quantities.jl:185

Possible fix, define
  fma(::Unitful.AbstractQuantity, ::Unitful.AbstractQuantity, ::Unitful.AbstractQuantity)

Ambiguity #18
Unitful.Level{L, S, T}(x) where {L, S, T} @ Unitful C:\Users\aames\.julia\dev\Unitful\src\types.jl:241
(::Type{T})(x::Base.TwicePrecision) where T<:Number @ Base twiceprecision.jl:266

Possible fix, define
  Unitful.Level{L, S, T}(::Base.TwicePrecision) where {L, S, T}

Ambiguity #19
(var"#ctor-self#"::Type{Unitful.Gain{L, S, T}} where {L, S, T<:Real})(val) @ Unitful C:\Users\aames\.julia\dev\Unitful\src\types.jl:257
(::Type{T})(x::Base.TwicePrecision) where T<:Number @ Base twiceprecision.jl:266

Possible fix, define
  Unitful.Gain{L, S, T}(::Base.TwicePrecision) where {L, S, T<:Real}

Ambiguity #20
muladd(x::Number, y::Unitful.AbstractQuantity, z::Unitful.AbstractQuantity) @ Unitful C:\Users\aames\.julia\dev\Unitful\src\quantities.jl:184
muladd(x::Unitful.AbstractQuantity, y::Number, z::Unitful.AbstractQuantity) @ Unitful C:\Users\aames\.julia\dev\Unitful\src\quantities.jl:185

Possible fix, define
  muladd(::Unitful.AbstractQuantity, ::Unitful.AbstractQuantity, ::Unitful.AbstractQuantity)

Ambiguity #21
Unitful.Level{L, S, T}(x) where {L, S, T} @ Unitful C:\Users\aames\.julia\dev\Unitful\src\types.jl:241
(::Type{T})(x::AbstractChar) where T<:Union{AbstractChar, Number} @ Base char.jl:50

Possible fix, define
  Unitful.Level{L, S, T}(::AbstractChar) where {L, S, T}

Ambiguity #22
(Unitful.Quantity{<:Any, D, U})(val) where {D, U} @ Unitful C:\Users\aames\.julia\dev\Unitful\src\types.jl:156
(::Type{T})(x::AbstractChar) where T<:Union{AbstractChar, Number} @ Base char.jl:50

Possible fix, define
  (Unitful.Quantity{<:Any, D, U})(::AbstractChar) where {D, U}

Ambiguity #23
(T::Type{<:Unitful.AbstractQuantity})(period::Union{Dates.Day, Dates.Hour, Dates.Microsecond, Dates.Millisecond, Dates.Minute, Dates.Nanosecond, Dates.Second, Dates.Week}) @ Unitful C:\Users\aames\.julia\dev\Unitful\src\dates.jl:60
(Unitful.Quantity{<:Any, D, U})(val) where {D, U} @ Unitful C:\Users\aames\.julia\dev\Unitful\src\types.jl:156

Possible fix, define
  (Unitful.Quantity{<:Any, D, U})(::Union{Dates.Day, Dates.Hour, Dates.Microsecond, Dates.Millisecond, Dates.Minute, Dates.Nanosecond, Dates.Second, Dates.Week}) where {D, U}

Method ambiguity: Test Failed at C:\Users\aames\.julia\packages\Aqua\utObL\src\ambiguities.jl:117
  Expression: success(pipeline(cmd; stdout = stdout, stderr = stderr))
Stacktrace:
 [1] macro expansion
   @ C:\Users\aames\.julia\juliaup\julia-1.9.0-beta2+0.x64.w64.mingw32\share\julia\stdlib\v1.9\Test\src\Test.jl:477 [inlined] 
 [2] _test_ambiguities(packages::Vector{Base.PkgId}; color::Nothing, exclude::Vector{Any}, detect_ambiguities_options::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ Aqua C:\Users\aames\.julia\packages\Aqua\utObL\src\ambiguities.jl:117
Test Summary:    | Fail  Total  Time
Method ambiguity |    1      1  3.5s
ERROR: LoadError: Some tests did not pass: 0 passed, 1 failed, 0 errored, 0 broken.
```

A similar result is produced by `Test.detect_ambiguities`:
```
julia> using Test, LinearAlgebra, Random, Unitful

julia> Test.detect_ambiguities(Base, Core, LinearAlgebra, Random; recursive=true)
11-element Vector{Tuple{Method, Method}}:
 (promote_rule(::Type{T}, ::Type{Level{L, R, S}}) where {L, R, S, T<:Real} @ Unitful C:\Users\aames\.julia\packages\Unitful\fbiNW\src\logarithm.jl:289, promote_rule(::Type{Bool}, ::Type{T}) where T<:Number @ Base bool.jl:4)
 ((var"#ctor-self#"::Type{Gain{L, S, T}} where {L, S, T<:Real})(val) @ Unitful C:\Users\aames\.julia\packages\Unitful\fbiNW\src\types.jl:257, (::Type{T})(x::Base.TwicePrecision) where T<:Number @ Base twiceprecision.jl:266)
 ((var"#ctor-self#"::Type{Gain{L, S, T}} where {L, S, T<:Real})(val) @ Unitful C:\Users\aames\.julia\packages\Unitful\fbiNW\src\types.jl:257, (::Type{T})(x::AbstractChar) where 
T<:Union{AbstractChar, Number} @ Base char.jl:50)
 (Level{L, S, T}(x) where {L, S, T} @ Unitful C:\Users\aames\.julia\packages\Unitful\fbiNW\src\types.jl:241, (::Type{T})(x::AbstractChar) where T<:Union{AbstractChar, Number} @ 
Base char.jl:50)
 ((Quantity{<:Any, D, U})(val) where {D, U} @ Unitful C:\Users\aames\.julia\packages\Unitful\fbiNW\src\types.jl:156, (::Type{T})(x::AbstractChar) where T<:Union{AbstractChar, Number} @ Base char.jl:50)
 (Level{L, S, T}(x) where {L, S, T} @ Unitful C:\Users\aames\.julia\packages\Unitful\fbiNW\src\types.jl:241, (::Type{T})(x::Base.TwicePrecision) where T<:Number @ Base twiceprecision.jl:266)
 (Level{L, S, T}(x) where {L, S, T} @ Unitful C:\Users\aames\.julia\packages\Unitful\fbiNW\src\types.jl:241, (::Type{T})(x::T) where T<:Number @ Core boot.jl:792)
 ((Quantity{<:Any, D, U})(val) where {D, U} @ Unitful C:\Users\aames\.julia\packages\Unitful\fbiNW\src\types.jl:156, (::Type{T})(x::Base.TwicePrecision) where T<:Number @ Base twiceprecision.jl:266)
 ((var"#ctor-self#"::Type{Gain{L, S, T}} where {L, S, T<:Real})(val) @ Unitful C:\Users\aames\.julia\packages\Unitful\fbiNW\src\types.jl:257, (::Type{T})(x::T) where T<:Number @ Core boot.jl:792)
 ((Quantity{<:Any, D, U})(val) where {D, U} @ Unitful C:\Users\aames\.julia\packages\Unitful\fbiNW\src\types.jl:156, (::Type{T})(x::T) where T<:Number @ Core boot.jl:792)       
 (promote_rule(::Type{T}, ::Type{Level{L, R, S}}) where {L, R, S, T<:Real} @ Unitful C:\Users\aames\.julia\packages\Unitful\fbiNW\src\logarithm.jl:289, promote_rule(::Type{S}, ::Type{T}) where {S<:AbstractIrrational, T<:Number} @ Base irrationals.jl:45)
```

### PR DESCRIPTION
**Pull request by sostock**
On Julia ≥1.1, this resolves all method ambiguities ~~(edit: all method ambiguities _that are found by `Aqua` or `Test.detect_ambiguities`_. #469 is still broken)~~. On Julia 1.0, there are 5 ambiguities remaining.

Closes #604.

Edit 2: this PR now resolves #469 as well.

### CODE REVIEW

File: src/logarithm.jl [hunk 1]
```diff
@@ -277,18 +277,12 @@ function (Base.promote_rule(::Type{Level{L1,S1,T1}}, ::Type{Level{L2,S2,T2}})
     end
 end
 
-function Base.promote_rule(::Type{Level{L,R,S}}, ::Type{Quantity{T,D,U}}) where {L,R,S,T,D,U}
-    return promote_type(S, Quantity{T,D,U})
-end
```
Comment (sostock) [inline src/logarithm.jl:282]: Removing this method does not resolve ambiguities. I just removed it because it isn’t necessary.
