### PR TITLE
Fix conversion of fractional units

### LINKED ISSUE #327: denominator error when converting fractional units
On Unitful 1.1.0,

```julia
julia> 1u"√m" |> u"√cm"
10.0 cm¹ᐟ²
```

After Unitful 1.2.0 with #323 (#319),

```julia
julia> 1u"√m" |> u"√cm"
ERROR: MethodError: no method matching denominator(::Float64)
Closest candidates are:
  denominator(::Integer) at rational.jl:232
  denominator(::Rational) at rational.jl:233
Stacktrace:
 [1] #s37#154 at /Users/tomyun/.julia/packages/Unitful/9XsxK/src/conversion.jl:41 [inlined]
 [2] #s37#154(::Any, ::Any, ::Any) at ./none:0
 [3] (::Core.GeneratedFunctionStub)(::Any, ::Vararg{Any,N} where N) at ./boot.jl:526
 [4] uconvert(::Unitful.FreeUnits{(cm¹ᐟ²,),𝐋¹ᐟ²,nothing}, ::Quantity{Int64,𝐋¹ᐟ²,Unitful.FreeUnits{(m¹ᐟ²,),𝐋¹ᐟ²,nothing}}) at /Users/tomyun/.julia/packages/Unitful/9XsxK/src/conversion.jl:78
 [5] FreeUnits at /Users/tomyun/.julia/packages/Unitful/9XsxK/src/types.jl:92 [inlined]
 [6] |>(::Quantity{Int64,𝐋¹ᐟ²,Unitful.FreeUnits{(m¹ᐟ²,),𝐋¹ᐟ²,nothing}}, ::Unitful.FreeUnits{(cm¹ᐟ²,),𝐋¹ᐟ²,nothing}) at ./operators.jl:823
 [7] top-level scope at REPL[28]:1
```

### PR DESCRIPTION
**Pull request by briochemc**
Fix #327

### CODE REVIEW

**Comment by briochemc** [comment]
@ajkeller34 could you check this?

BTW, I think the comments in line 14–15 that say:

```julia
    # fact1 is what would need to be multiplied to get to base SI units
    # fact2 is what would be multiplied to get from the result to base SI units
```

should be updated to refer to `inex1` and `inex2` instead? (But I'm not sure, so I did not suggest a correction for that.)

File: src/conversion.jl [hunk 1]
```diff
@@ -38,10 +38,10 @@ Find the conversion factor from unit `t` to unit `s`, e.g. `convfact(m,cm) = 0.0
         end
     end
 
-    if denominator(ex) == 1 # Use an integer for conversion if the ratio is whole
-        ex = numerator(ex)  # so that, e.g., uconvert(s, 1minute) = 60s
+    if ex isa Rational && denominator(ex) == 1
+        ex = numerator(ex)
     end
-
+
```
Comment (giordano) [inline src/conversion.jl:44]:
```suggestion

```
